[serve]
port = 8090
[[proxy]]
backend = "http://localhost:3001/api/"
frontend = "/api/"
[[copy]]
source = "robots.txt"
destination = "robots.txt"

[build]
target = "index.html"
css = [
    "assets/styles.css",
    "src/profile/billing.css",
    "src/profile/settings.css",
    "src/pages/money.css",
    "src/pages/home.css",
    "src/auth/connect.css",
    "src/auth/signup.css",
]
