version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    environment:
      - ENVIRONMENT=staging
      - DATABASE_URL=/app/data/database.db
      - FRONTEND_URL=${COOLIFY_FQDN:-http://localhost}
      - SERVER_URL_OAUTH=${COOLIFY_FQDN:-http://localhost:3000}
    volumes:
      - data:/app/data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    # No runtime; builds dist/ to volume

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro  # Mount built dist/
      - ./backend/static:/usr/share/nginx/backend-static:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  data:
  frontend_dist:  # Captures /app/dist from build

networks:
  app-network:
    driver: bridge
