# Lightfriend Docker Commands

# Default recipe (show available commands)
default:
    @just --list

# Build all Docker images (multi-platform: amd64 + arm64)
build:
    @echo "Building for multiple platforms (amd64 + arm64)..."
    @echo "This enables cross-compatibility but takes longer."
    cd docker && docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        -t lightfriend-core:latest \
        -f core/Dockerfile \
        --load \
        .. || echo "Note: --load doesn't support multi-platform. Use 'just build-push' to push to registry."
    cd docker && docker compose build --no-cache postgres synapse mautrix-whatsapp mautrix-signal mautrix-messenger mautrix-instagram signald

# Build for current platform only (faster, single architecture)
build-native:
    @echo "Building for current platform only (faster)..."
    cd docker && docker compose build

# Build and push multi-platform images to registry
build-push REGISTRY="docker.io/yourusername":
    @echo "Building and pushing multi-platform images to {{REGISTRY}}..."
    cd docker && docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        -t {{REGISTRY}}/lightfriend-core:latest \
        -f core/Dockerfile \
        --push \
        ..

# Build only the core image (current platform)
build-core:
    cd docker && docker compose build core

# Build core for multiple platforms
build-core-multi:
    @echo "Building core for multiple platforms..."
    cd docker && docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t lightfriend-core:latest \
        -f core/Dockerfile \
        --load \
        .. || echo "Note: Use 'just build-core-push' to push multi-platform image."

# Fast build (uses release-fast profile with fewer optimizations)
build-fast:
    @echo "Building with faster compile settings (less optimized binary)..."
    cd docker && CARGO_PROFILE=release-fast docker compose build core

# Start all services (generates configs first)
up:
    @just setup-configs
    cd docker && docker compose up -d
    @echo "Services starting..."
    @echo "Frontend: http://localhost:8080"
    @echo "Backend API: http://localhost:3000"
    @echo "Synapse: http://localhost:8008"

# Start services with logs
up-logs:
    cd docker && docker compose up

# Stop all services
down:
    cd docker && docker compose down

# Stop and remove all volumes (WARNING: deletes all data)
down-volumes:
    cd docker && docker compose down -v

# Restart all services
restart:
    cd docker && docker compose restart

# Restart only core service
restart-core:
    cd docker && docker compose restart core

# View logs for all services
logs:
    cd docker && docker compose logs -f

# View logs for core service only
logs-core:
    cd docker && docker compose logs -f core

# View logs for synapse
logs-synapse:
    cd docker && docker compose logs -f synapse

# View logs for a specific bridge (usage: just logs-bridge whatsapp)
logs-bridge bridge:
    cd docker && docker compose logs -f mautrix-{{bridge}}

# Check status of all services
status:
    cd docker && docker compose ps

# Generate new secrets for .env file
# NOTE: Bridge tokens are now auto-generated by setup-configs.sh
generate-secrets:
    @echo "# Core secrets"
    @echo "JWT_SECRET_KEY=$(openssl rand -base64 32)"
    @echo "JWT_REFRESH_KEY=$(openssl rand -base64 32)"
    @echo "ENCRYPTION_KEY=$(openssl rand -base64 32)"
    @echo ""
    @echo "# Matrix & Database"
    @echo "MATRIX_HOMESERVER_SHARED_SECRET=$(openssl rand -hex 32)"
    @echo "SYNAPSE_DB_PASSWORD=$(openssl rand -base64 32)"
    @echo "POSTGRES_PASSWORD=$(openssl rand -base64 32)"
    @echo ""
    @echo "# Bridge configuration"
    @echo "DOUBLE_PUPPET_SECRET=$(openssl rand -base64 32)"

# Generate config files from templates using .env variables
setup-configs:
    @echo "Generating configuration files from .env..."
    cd docker && ./setup-configs.sh

# Enter core container shell
shell-core:
    cd docker && docker compose exec core /bin/bash

# Enter synapse container shell
shell-synapse:
    cd docker && docker compose exec synapse /bin/bash

# Enter postgres container shell
shell-postgres:
    cd docker && docker compose exec postgres psql -U postgres

# Run database migrations in core
migrate:
    cd docker && docker compose exec core diesel migration run

# Create a new Synapse admin user
create-admin user password:
    cd docker && docker compose exec synapse register_new_matrix_user \
        -c /data/homeserver.yaml \
        -u {{user}} \
        -p {{password}} \
        --admin

# Clean up Docker resources (images, containers, networks)
clean:
    docker system prune -f

# Full rebuild (stop, clean, rebuild, start)
rebuild: down clean build up

# Show Docker disk usage
disk-usage:
    docker system df

# Development: Run backend locally (not in Docker)
dev-backend:
    cd backend && cargo run

# Development: Run frontend locally (not in Docker)
dev-frontend:
    cd frontend && trunk serve

# Development: Run tests for backend
test-backend:
    cd backend && cargo test

# Development: Run tests for frontend  
test-frontend:
    cd frontend && cargo test
