# Lightfriend Docker Commands

# Default recipe (show available commands)
default:
    @just --list

# Build all Docker images
build:
    cd docker && docker compose build

# Build only the core image
build-core:
    cd docker && docker compose build core

# Build backend for Linux using Docker, then create image - USE THIS IF RUNNING OUT OF MEMORY
build-prebuilt:
    @echo "Building backend for Linux in Docker (may take 10-15 minutes)..."
    docker run --rm \
        -v "{{justfile_directory()}}/backend:/app" \
        -w /app \
        rust:1.85-bookworm \
        sh -c "apt-get update && apt-get install -y libsqlite3-dev pkg-config libssl-dev lld && cargo build --release"
    @echo "Creating Docker image with pre-built binary..."
    cd docker && docker build -f core/Dockerfile.prebuilt -t lightfriend-core ..

# Start all services (generates configs first)
up:
    @just setup-configs
    cd docker && docker compose up -d
    @echo "Services starting..."
    @echo "Frontend: http://localhost:8080"
    @echo "Backend API: http://localhost:3000"
    @echo "Synapse: http://localhost:8008"

# Start services with logs
up-logs:
    cd docker && docker compose up

# Stop all services
down:
    cd docker && docker compose down

# Stop and remove all volumes (WARNING: deletes all data)
down-volumes:
    cd docker && docker compose down -v

# Restart all services
restart:
    cd docker && docker compose restart

# Restart only core service
restart-core:
    cd docker && docker compose restart core

# View logs for all services
logs:
    cd docker && docker compose logs -f

# View logs for core service only
logs-core:
    cd docker && docker compose logs -f core

# View logs for synapse
logs-synapse:
    cd docker && docker compose logs -f synapse

# View logs for a specific bridge (usage: just logs-bridge whatsapp)
logs-bridge bridge:
    cd docker && docker compose logs -f mautrix-{{bridge}}

# Check status of all services
status:
    cd docker && docker compose ps

# Generate new secrets for .env file
# NOTE: Bridge tokens are now auto-generated by setup-configs.sh
generate-secrets:
    @echo "# Core secrets"
    @echo "JWT_SECRET_KEY=$(openssl rand -base64 32)"
    @echo "JWT_REFRESH_KEY=$(openssl rand -base64 32)"
    @echo "ENCRYPTION_KEY=$(openssl rand -base64 32)"
    @echo ""
    @echo "# Matrix & Database"
    @echo "MATRIX_HOMESERVER_SHARED_SECRET=$(openssl rand -hex 32)"
    @echo "SYNAPSE_DB_PASSWORD=$(openssl rand -base64 32)"
    @echo "POSTGRES_PASSWORD=$(openssl rand -base64 32)"
    @echo ""
    @echo "# Bridge configuration"
    @echo "DOUBLE_PUPPET_SECRET=$(openssl rand -base64 32)"

# Generate config files from templates using .env variables
setup-configs:
    @echo "Generating configuration files from .env..."
    cd docker && ./setup-configs.sh

# Enter core container shell
shell-core:
    cd docker && docker compose exec core /bin/bash

# Enter synapse container shell
shell-synapse:
    cd docker && docker compose exec synapse /bin/bash

# Enter postgres container shell
shell-postgres:
    cd docker && docker compose exec postgres psql -U postgres

# Run database migrations in core
migrate:
    cd docker && docker compose exec core diesel migration run

# Create a new Synapse admin user
create-admin user password:
    cd docker && docker compose exec synapse register_new_matrix_user \
        -c /data/homeserver.yaml \
        -u {{user}} \
        -p {{password}} \
        --admin

# Clean up Docker resources (images, containers, networks)
clean:
    docker system prune -f

# Full rebuild (stop, clean, rebuild, start) - uses prebuilt method
rebuild: down clean build-prebuilt up

# Show Docker disk usage
disk-usage:
    docker system df

# Development: Run backend locally (not in Docker)
dev-backend:
    cd backend && cargo run

# Development: Run frontend locally (not in Docker)
dev-frontend:
    cd frontend && trunk serve

# Development: Run tests for backend
test-backend:
    cd backend && cargo test

# Development: Run tests for frontend  
test-frontend:
    cd frontend && cargo test
