-- Add matrix_event_id for deterministic event-level dedup.
-- The existing 5-minute content-window dedup in insert_message catches
-- bridge re-emissions but misses matrix-sdk re-sync redeliveries that
-- happen >5 min apart (observed: same WA messages stored twice, 14 min
-- apart, when matrix-sdk re-synced from a rewound `since` token).
-- The Matrix event_id is generated by the homeserver, globally unique,
-- and immutable, so the same event re-streamed by sync still carries
-- the same id.
--
-- Nullable + partial unique index: backfill rows from before this
-- migration won't have an event_id and shouldn't trigger constraint
-- violations against each other.
ALTER TABLE ont_messages
ADD COLUMN matrix_event_id TEXT;

CREATE UNIQUE INDEX idx_ont_messages_matrix_event_id
ON ont_messages (user_id, matrix_event_id)
WHERE matrix_event_id IS NOT NULL;
